### ISSUE TITLE
SqueezePlay stopped working after upgrade to Mint 21.1

### ISSUE THREAD

**Issue by H34dl3ss** [ralph-irving/squeezeplay#11]
The app is starting, everything else seems to work but no sound is played.

Please advise, what information is needed to troubleshoot.
The issue came up on 3 different machines after upgrading to Mint 21.1

**Comment by ralph-irving** [comment]
What version and is it alsa or pulse?
Have you tried them both?

**Comment by H34dl3ss** [comment]
I used squeezeplay-8.0.1-1402-x86_64.tgz with Mint 20.

I tried the pulse version now and this one is working with Mint 21.1
Thanks for directing me!

I wasn't aware about the sound architecture of Linux - seasoned Windows user here.
Because of your question I realized that I had to check for the differences.
