### ISSUE TITLE
Constantly reconnecting

### ISSUE THREAD

**Issue by Rotozaza** [ralph-irving/squeezeplay#2]
I've tried 7.8.0r685 to 7.8.0r959, they all reconnect every 10 second. Once music plays it streams uninterrupted. 

Choose Player reconnects by second, but works when clickin at the right moment. 

Any idea? 

Latest Windows 10 and LMS 7.7.2 - r33893 (maybe the later?)

**Comment by ralph-irving** [comment]
I can't reproduce this with LMS 7.8.1 or 7.9.1.  Might be the windows firewall if enabled, or antivirus software.
