### ISSUE TITLE
compile error squeezeplay on Debian 10

### ISSUE THREAD

**Issue by RunningForNoReason** [ralph-irving/squeezeplay#5]
Trying to compile squeezeplay on Debian 10 and get this error:

gcc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"SDL_gfx\" -DVERSION=\"2.0.15\" -DX_DISPLAY_MISSING=1 -DBUILD_DLL -I. -I. -I/home/hans/Downloads/squeezeplay/build/linux/include -I/home/hans/Downloads/squeezeplay/build/linux/include/SDL -I/home/hans/Downloads/squeezeplay/build/linux/include/freetype2 -s -O3 -fPIC -march=core2 -DUSE_MMX -I/home/hans/Downloads/squeezeplay/build/linux/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -MT SDL_imageFilter.lo -MD -MP -MF .deps/SDL_imageFilter.Tpo -c SDL_imageFilter.c  -fPIC -DPIC -o SDL_imageFilter.lo
SDL_imageFilter.c: Assembler messages:
SDL_imageFilter.c:34: Error: `pusha' is not supported in 64-bit mode
SDL_imageFilter.c:38: Error: `popa' is not supported in 64-bit mode

**Comment by ralph-irving** [comment]
64bit doesn't support MMX instructions.  Modify Makefile.linux and disable mmx
Change
USE_MMX=--enable-mmx
to
USE_MMX=--disable-mmx

Then issue make -f Makefile.linux clean and then rebuild.

**Comment by RunningForNoReason** [comment]
Works perfect tx!
