### ISSUE TITLE
wpa_supplicant 2.9 : 404 not found

### ISSUE THREAD

**Issue by kalon33** [ralph-irving/squeezeplay#6]
Sorry to post issue here as it is squeezeos related, but issue tracker is not enabled there...
   
I just noticed this morning that https://hostap.epitest.fi/releases/wpa_supplicant-2.9.tar.gz returns a 404 now, so it is not possible to build squeezeos from source as no wpa_supplicant 2.9 tarball source is available anymore.

Could you please fix? If needed I have the tarball here, but I imagine you too.

Best regards, and really huge thanks for maintaining squeezeplay/squeezeos community firmware.

**Comment by ralph-irving** [comment]
I've updated all references to the outdated url in the squeezeos repository and enabled the issue tracker.

**Comment by kalon33** [comment]
Thanks :)
